---
- name: Attempt Droplet Connection
  hosts: all
  remote_user: root
  gather_facts: no

  tasks:

  - name: Attempt Connection after 40 seconds
    wait_for_connection:
      delay: 40
      timeout: 120